# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-27 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('size', models.CharField(choices=[('TN', 'Tiny'), ('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], default='MD', max_length=2)),
                ('friendliness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('trainability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('sheddingamount', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('exerciseneeds', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=1000)),
                ('color', models.CharField(blank=True, max_length=1000)),
                ('favoritefood', models.CharField(blank=True, max_length=1000)),
                ('favoritetoy', models.CharField(blank=True, max_length=1000)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('userid', models.CharField(blank=True, max_length=1000)),
                ('requestor', models.GenericIPAddressField()),
            ],
        ),
    ]
